import pathlib
from configparser import ConfigParser
from os import path

from configgen.command import Command
from configgen.controllers import generate_sdl_controller_config
from configgen.generators.generator import Generator
from configgen.systemFiles import CONF, SAVES, SCREENSHOTS
from configgen.utils.buildargs import parse_args


class EDuke32Generator(Generator):
    def generate(
        self,
        system,
        rom,
        players_controllers,
        metadata,
        guns,
        wheels,
        game_resolution,
    ):
        # Core is either eduke32 or fury
        core = system.config["core"]
        config_dir = f"{CONF}/{core}"
        saves_dir = f"{SAVES}/{core}"
        config_file = f"{config_dir}/{core}.cfg"

        # A script file with console commands that are always ran when the game starts
        script_file = f"{config_dir}/autoexec.cfg"
        for directory in [config_dir, saves_dir]:
            if not pathlib.Path(directory).exists():
                pathlib.Path(directory).mkdir()

        if not pathlib.Path(config_file).exists():
            with pathlib.Path(config_file).open("x"):
                pass

        parser = ConfigParser(interpolation=None)

        # Override optionxform to stop implicit case conversions
        parser.optionxform = lambda optionstr: str(optionstr)

        # Configuration options found here: https://wiki.eduke32.com/wiki/Configuration_file_options
        # NB: Not all configuration options listed actually work e.g. showFPS, etc.
        # NB: In eduke32 configs, booleans must be integers
        with pathlib.Path(config_file).open() as config:
            parser.read_file(config)
        if not parser.has_section("Screen Setup"):
            parser.add_section("Screen Setup")

        if game_resolution["width"] < game_resolution["height"]:
            game_resolution["width"], game_resolution["height"] = (
                game_resolution["height"],
                game_resolution["width"],
            )

        parser.set("Screen Setup", "ScreenWidth", str(game_resolution["width"]))
        parser.set("Screen Setup", "ScreenHeight", str(game_resolution["height"]))

        # The game should always be fullscreen
        parser.set("Screen Setup", "ScreenMode", "1")
        with pathlib.Path(config_file).open("w") as config:
            parser.write(config)
        with pathlib.Path(script_file).open("w") as script:
            script.write(
                f"// This file is automatically generated by eduke32Generator.py\n"
                f'bind "F12" "screenshot"\n'
                f'screenshot_dir "{SCREENSHOTS}"\n'
                f'r_showfps "{1 if system.getOptBoolean("showFPS") else 0}"\n'
                f"echo REG-Linux\n",  # Easy check when debugging
            )
        command_array = [
            core,
            "-cfg",
            config_file,
            "-nologo" if system.getOptBoolean("nologo") else "",
        ]
        if core == "fury":
            command_array += ["-gamegrp", path.basename(rom), "-j", path.dirname(rom)]
        else:
            result = parse_args(command_array, rom)
            if not result.okay:
                raise Exception(result.message)

        return Command(
            array=command_array,
            env={
                "SDL_GAMECONTROLLERCONFIG": generate_sdl_controller_config(
                    players_controllers,
                ),
            },
        )
