from configgen.generators.Generator import Generator
from configgen.Command import Command
from os import path, mkdir
from configparser import ConfigParser
from configgen.utils.buildargs import parse_args
from configgen.systemFiles import CONF, SAVES, SCREENSHOTS
from configgen.controllers import generate_sdl_controller_config


class EDuke32Generator(Generator):
    def generate(
        self, system, rom, playersControllers, metadata, guns, wheels, gameResolution
    ):
        # Core is either eduke32 or fury
        core = system.config["core"]
        config_dir = f"{CONF}/{core}"
        saves_dir = f"{SAVES}/{core}"
        config_file = f"{config_dir}/{core}.cfg"

        # A script file with console commands that are always ran when the game starts
        script_file = f"{config_dir}/autoexec.cfg"
        for dir in [config_dir, saves_dir]:
            if not path.exists(dir):
                mkdir(dir)

        if not path.exists(config_file):
            with open(config_file, "x"):
                pass

        parser = ConfigParser(interpolation=None)

        # Override optionxform to stop implicit case conversions
        parser.optionxform = lambda optionstr: str(optionstr)

        # Configuration options found here: https://wiki.eduke32.com/wiki/Configuration_file_options
        # NB: Not all configuration options listed actually work e.g. showFPS, etc.
        # NB: In eduke32 configs, booleans must be integers
        with open(config_file, "r") as config:
            parser.read_file(config)
        if not parser.has_section("Screen Setup"):
            parser.add_section("Screen Setup")

        if gameResolution["width"] < gameResolution["height"]:
            gameResolution["width"], gameResolution["height"] = (
                gameResolution["height"],
                gameResolution["width"],
            )

        parser.set("Screen Setup", "ScreenWidth", str(gameResolution["width"]))
        parser.set("Screen Setup", "ScreenHeight", str(gameResolution["height"]))

        # The game should always be fullscreen
        parser.set("Screen Setup", "ScreenMode", "1")
        with open(config_file, "w") as config:
            parser.write(config)
        with open(script_file, "w") as script:
            script.write(
                f"// This file is automatically generated by eduke32Generator.py\n"
                f'bind "F12" "screenshot"\n'
                f'screenshot_dir "{SCREENSHOTS}"\n'
                f'r_showfps "{1 if system.getOptBoolean("showFPS") else 0}"\n'
                f"echo REG-Linux\n"  # Easy check when debugging
            )
        commandArray = [
            core,
            "-cfg",
            config_file,
            "-nologo" if system.getOptBoolean("nologo") else "",
        ]
        if core == "fury":
            commandArray += ["-gamegrp", path.basename(rom), "-j", path.dirname(rom)]
        else:
            result = parse_args(commandArray, rom)
            if not result.okay:
                raise Exception(result.message)

        return Command(
            array=commandArray,
            env={
                "SDL_GAMECONTROLLERCONFIG": generate_sdl_controller_config(
                    playersControllers
                )
            },
        )
