################################################################################
#
# OpenMW
#
################################################################################

OPENMW_VERSION = openmw-0.48.0
OPENMW_SITE = $(call,github,OpenMW,openmw)
OPENMW_DEPENDENCIES = libgl lz4 yaml-cpp bullet ffmpeg openal sqlite sdl2
OPENMW_DEPENDENCIES += boost fontconfig freetype poppler cairo
OPENMW_SUPPORTS_IN_SOURCE_BUILD = NO

OPENMW_CONF_OPTS += -DCMAKE_BUILD_TYPE=Release
OPENMW_CONF_OPTS += -DBUILD_SHARED_LIBS=OFF
OPENMW_CONF_OPTS += -DOPENMW_UNITY_BUILD=TRUE
OPENMW_CONF_OPTS += -DENABLE_TEST=OFF
OPENMW_CONF_OPTS += -DBUILD_DOCS=OFF
OPENMW_CONF_OPTS += -DBUILD_LAUNCHER=OFF
OPENMW_CONF_OPTS += -DBUILD_OPENCS=OFF
OPENMW_CONF_OPTS += -DBUILD_WIZARD=OFF
OPENMW_CONF_OPTS += -DBUILD_BSATOOL=OFF
OPENMW_CONF_OPTS += -DBUILD_ESMTOOL=OFF
OPENMW_CONF_OPTS += -DBUILD_NIF_TEST=OFF
OPENMW_CONF_OPTS += -DBUILD_MWINIIMPORTER=OFF
OPENMW_CONF_OPTS += -DBUILD_ESSIMPORTER=OFF
OPENMW_CONF_OPTS += -DBUILD_NAVMESHTOOL=OFF
OPENMW_CONF_OPTS += -DBUILD_BULLETOBJECTTOOL=OFF
OPENMW_CONF_OPTS += -DOPENMW_USE_SYSTEM_OSG=OFF
OPENMW_CONF_OPTS += -DOPENMW_USE_SYSTEM_MYGUI=OFF

#OPENMW_CONF_OPTS += -DOPENMW_LTO_BUILD=ON

#OPENMW_CONF_OPTS += -DUSE_LUAJIT=OFF

OPENMW_CONF_OPTS += -DOSG_CPP_EXCEPTIONS_AVAILABLE=ON \
	-D_OPENTHREADS_ATOMIC_USE_GCC_BUILTINS=1 \
	-DOPENTHREADS_ATOMIC_USE_MUTEX=ON

# MyGUI config options
OPENMW_CONF_OPTS += -DMYGUI_RENDERSYSTEM=1

ifeq ($(BR2_PACKAGE_XORG7),y)
OPENMW_DEPENDENCIES += xlib_libX11 xlib_libXrandr fltk
OPENMW_CONF_OPTS += -DOSG_WINDOWING_SYSTEM=X11
else
OPENMW_CONF_OPTS += -DOSG_WINDOWING_SYSTEM=None
endif

$(eval $(cmake-package))
