#!/bin/dash

DAEMON="pigpiod"
PIDFILE="/var/run/pigpio.pid"
PIGPIOD_ARGS=""
[ -r "/etc/default/pigpio" ] && . "/etc/default/pigpio"

start() {
	printf 'Starting %s: ' "$DAEMON"
	{ start-stop-daemon -S -q -x "/usr/bin/$DAEMON" -- $PIGPIOD_ARGS && echo "OK"; } || { echo "FAIL"; return 1; }
}

stop() {
	printf 'Stopping %s: ' "$DAEMON"
	{ start-stop-daemon -K -q -p "$PIDFILE" && echo "OK"; } || { echo "FAIL"; return 1; }
}

restart() {
	stop
	sleep 1
	start
}

case "$1" in
	start|stop|restart)
		"$1";;
	reload)
		# Restart, since there is no true "reload" feature.
		restart;;
	status)
		{ pgrep -x "pigpiod" > /dev/null && echo "pigpiod is running."; } || { echo "pigpiod is not running."; }
		;;
	enable|enabled|disable|disabled) ;;
	*)
		printf '%s\n' "Usage: $0 {start|stop|restart|enable|disable|status}" >&2
		exit 1
		;;
esac
