#!/bin/sh

case "$1" in
    start)
        # Boot splash with "insert coin"
        /usr/sbin/plymouthd --mode=boot --graphical-boot --attach-to-session
        /usr/bin/plymouth --show-splash
    ;;
    stop)
        # Shutdown splash with "game over" was set by S12populateshare
        /usr/bin/plymouth --wait quit --retain-splash
    ;;
    *)
esac

exit $?
