#!/bin/dash
#
# Starts irqbalance
#

EXEC="/usr/sbin/irqbalance"
ARGS=""
PID="/var/run/irqbalance.pid"

case "$1" in
  start)
    printf "Starting irqbalance: "
    # ignore/ban irq(s) from irqbalance
    for i in $(/usr/bin/awk -F':' '/rdma|vsync/{print $1}' </proc/interrupts | /bin/sed 's/\ //g'); do
        ARGS="$ARGS --banirq=$i"
    done
    # for irqbalance socket /run/irqbalance/irqbalance<pid>.sock
    mkdir -p /run/irqbalance
    if start-stop-daemon -S -q -p $PID -x $EXEC -- $ARGS ; then
        echo "OK"
    else
        echo "FAILED"
        exit 1
    fi
    ;;
  stop)
    printf "Stopping irqbalance: "
    start-stop-daemon -K -q -p $PID
    echo "OK"
    ;;
  restart|reload)
    $0 stop
    $0 start
    ;;
  *)
    exec echo "Usage: $0 {start|stop|restart|reload}"
    exit 1
esac
