#!/bin/sh
BOOTCONF="/boot/batocera-boot.conf"

. /etc/profile.d/xdg.sh
. /etc/profile.d/dbus.sh

case "$1" in
	start)
		/etc/init.d/S02plymouth stop
		enabled="$(/usr/bin/batocera-settings-get system.es.atstartup)"
		if [ "$enabled" != "0" ]; then
			environment="$(/usr/bin/batocera-settings-get-master system.es.environment)"
			if [ "$environment" = "sway" ]; then
				SWAY_LOG_FILE=/userdata/system/logs/sway.log
				WLR_LIBINPUT_NO_DEVICES=1 /usr/bin/sway -d > ${SWAY_LOG_FILE} 2>&1 &
			else
				%REGLINUX_EMULATIONSTATION_CMD% %REGLINUX_EMULATIONSTATION_POSTFIX%
			fi
		fi
		;;

	stop)
        	emulationstation-standalone --stop-rebooting
		killall openbox   2>/dev/null # for xorg
		killall sway      2>/dev/null # for wayland
		killall emulationstation 2>/dev/null
		killall touchegg 2>/dev/null
		if [ $? -eq 0 ]; then
			sleep 20 &
			watchdog=$!
			while ! [ -z $(pidof emulationstation) ]; do
				sleep 0.25
				$(kill -0 $watchdog) || exit
			done
			kill -9 $watchdog
		fi
		;;

	restart|reload)
		"$0" stop
		"$0" start
		;;

	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac

exit $?

