#!/bin/bash
case "$1" in
  start)
    # Look for a swap partition
    SWAP=$(blkid -c /dev/null -l -o device -t TYPE=swap)
    # If no swap partition use file
    if [ -z "$SWAP" ]; then
      SWAP="/userdata/system/swapfile"
      if [ ! -f "$SWAP" ]; then
        fallocate -l 512M "$SWAP"
        chmod 600 "$SWAP"
        mkswap "$SWAP"
      fi
    fi
    swapon -f "$SWAP"
    ;;
  stop)
    swapoff -a
    ;;
  restart|reload)
    "$0" stop
    "$0" start
    ;;
  enabled|disabled)
    ;;
  status)
    [ -n "$(swapon --show)" ] && echo "SWAP status: enabled" || echo "SWAP status: disabled"
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|reload|enabled|disabled|status}"
    exit 1
esac
