#!/bin/dash
case "$1" in
  start|enabled)
    # Look for a swap partition
    SWAP=$(blkid -c /dev/null -l -o device -t TYPE=swap)
    # If no swap partition use file
    if [ -z "$SWAP" ]; then
      SWAP="/userdata/system/swapfile"
      if [ ! -f "$SWAP" ]; then
        fallocate -l 512M "$SWAP"
        chmod 600 "$SWAP"
        mkswap "$SWAP"
      fi
    fi
    swapon -f "$SWAP"
    ;;
  stop|disabled) swapoff -a ;;
  restart|reload)
    "$0" stop
    exec "$0" start
    ;;
  status)
    [ -n "$(swapon --show)" ] && echo "SWAP status: enabled" || echo "SWAP status: disabled"
    ;;
  *)
    printf 'Usage: %s {start|stop|restart|reload|enabled|disabled|status}\n' "$0" >&2
    exit 1
esac