#!/bin/bash

# Check if vulkaninfo exists
if [ ! -x "/usr/bin/vulkaninfo" ]; then
    echo "Vulkan not found"
    exit 1
fi

# Run vulkaninfo --summary and cache results
VKINFO="$(vulkaninfo --summary)"

# Function to list Vulkan GPU devices
list_devices() {
   echo "${VKINFO}" | grep deviceName | awk -F'= ' '{print $2}'
}

# Function to count the number of Vulkan GPU devices
num_devices() {
    list_devices | wc -l
}

# Function to check if a discrete GPU exists
has_discrete() {
    echo "${VKINFO}" | grep -q PHYSICAL_DEVICE_TYPE_DISCRETE_GPU
    if [ $? -eq 0 ]; then
        echo "true"
    else
        echo "false"
    fi
}

# Function to check if an integrated GPU exists
has_integrated() {
    echo "${VKINFO}" | grep -q PHYSICAL_DEVICE_TYPE_INTEGRATED_GPU
    if [ $? -eq 0 ]; then
        echo "true"
    else
        echo "false"
    fi
}

# Function to retrieve the UUID of the discrete GPU
discrete_uuid() {
    device_type_output=$(echo "${VKINFO}" | grep deviceType)
    discrete_gpu_index=$(echo "$device_type_output" | grep -n PHYSICAL_DEVICE_TYPE_DISCRETE_GPU | cut -d: -f1)
    if [ -z "$discrete_gpu_index" ]; then
        echo "No discrete GPU found."
        exit 1
    fi

    device_uuid=$(echo "${VKINFO}" | grep deviceUUID | sed -n "${discrete_gpu_index}p" | awk -F'=' '{print $2}' | tr -d '[:space:]')
    if [ -z "$device_uuid" ]; then
        echo "Failed to retrieve UUID for the discrete GPU."
        exit 1
    fi

    echo "$device_uuid"
}

# Function to retrieve the UUID of the integrated GPU
integrated_uuid() {
    device_type_output=$(echo "${VKINFO}" | grep deviceType)
    integrated_gpu_index=$(echo "$device_type_output" | grep -n PHYSICAL_DEVICE_TYPE_INTEGRATED_GPU | cut -d: -f1)
    if [ -z "$integrated_gpu_index" ]; then
        echo "No integrated GPU found."
        exit 1
    fi

    device_uuid=$(echo "${VKINFO}" | grep deviceUUID | sed -n "${integrated_gpu_index}p" | awk -F'=' '{print $2}' | tr -d '[:space:]')
    if [ -z "$device_uuid" ]; then
        echo "Failed to retrieve UUID for the integrated GPU."
        exit 1
    fi

    echo "$device_uuid"
}

# Function to retrieve the name of the discrete GPU
discrete_name() {
    device_type_output=$(echo "${VKINFO}" | grep deviceType)
    discrete_gpu_index=$(echo "$device_type_output" | grep -n PHYSICAL_DEVICE_TYPE_DISCRETE_GPU | cut -d: -f1)
    if [ -z "$discrete_gpu_index" ]; then
        echo "No discrete GPU found."
        exit 1
    fi

    device_name=$(echo "${VKINFO}" | grep deviceName | sed -n "${discrete_gpu_index}p" | awk -F'= ' '{print $2}')
    if [ -z "$device_name" ]; then
        echo "Failed to retrieve name for the discrete GPU."
        exit 1
    fi

    echo "$device_name"
}

# Function to retrieve the name of the integrated GPU
integrated_name() {
    device_type_output=$(echo "${VKINFO}" | grep deviceType)
    integrated_gpu_index=$(echo "$device_type_output" | grep -n PHYSICAL_DEVICE_TYPE_INTEGRATED_GPU | cut -d: -f1)
    if [ -z "$integrated_gpu_index" ]; then
        echo "No integrated GPU found."
        exit 1
    fi

    device_name=$(vulkaninfo | grep deviceName | sed -n "${integrated_gpu_index}p" | awk -F'= ' '{print $2}')
    if [ -z "$device_name" ]; then
        echo "Failed to retrieve name for the integrated GPU."
        exit 1
    fi

    echo "$device_name"
}

# Function to retrieve the index (GPU number) of the discrete GPU
discrete_index() {
    device_type_output=$(echo "${VKINFO}" | grep deviceType)
    discrete_gpu_index=$(echo "$device_type_output" | grep -n PHYSICAL_DEVICE_TYPE_DISCRETE_GPU | cut -d: -f1)
    # Subtract 1 from the index to get the Vulkan GPU number
    discrete_gpu_index=$((discrete_gpu_index - 1))
    if [ -z "$discrete_gpu_index" ]; then
        echo "No discrete GPU found."
        exit 1
    fi

    echo "$discrete_gpu_index"
}

# Function to retrieve the index (GPU number) of the integrated GPU
integrated_index() {
    device_type_output=$(echo "${VKINFO}" | grep deviceType)
    integrated_gpu_index=$(echo "$device_type_output" | grep -n PHYSICAL_DEVICE_TYPE_INTEGRATED_GPU | cut -d: -f1)
    # Subtract 1 from the index to get the Vulkan GPU number
    integrated_gpu_index=$((integrated_gpu_index - 1))
    if [ -z "$integrated_gpu_index" ]; then
        echo "No integrated GPU found."
        exit 1
    fi

    echo "$integrated_gpu_index"
}

# Function to check if Vulkan is available
has_vulkan() {
    echo "${VKINFO}" | grep -q deviceName
    if [ $? -eq 0 ]; then
        echo "true"
    else
        echo "false"
    fi
}

vulkan_version() {
    if [ $(has_vulkan) = "true" ]; then
        if [ $(has_discrete) = "true" ]; then
            discreteIndex=$(discrete_index)
            apiVersion=$(echo "${VKINFO}" | grep -A8 "GPU$discreteIndex" | awk '/apiVersion/ {print $3}')
            echo $apiVersion
        else
            apiVersion=$(echo "${VKINFO}" | grep -A8 "GPU0" | awk '/apiVersion/ {print $3}')
            echo $apiVersion
        fi
    else
        echo "No Vulkan driver found!"
    fi
}

# Handle input options
case "$1" in
    "listDevices")
        list_devices
        ;;
    "numDevices")
        num_devices
        ;;
    "hasDiscrete")
        has_discrete
        ;;
    "hasIntegrated")
        has_integrated
        ;;
    "discreteUUID")
        discrete_uuid
        ;;
    "integratedUUID")
        integrated_uuid
        ;;
    "discreteName")
        discrete_name
        ;;
    "integratedName")
        integrated_name
        ;;
    "discreteIndex")
        discrete_index
        ;;
    "integratedIndex")
        integrated_index
        ;;
    "hasVulkan")
        has_vulkan
        ;;
    "vulkanVersion")
        vulkan_version
        ;;
    *)
        echo "Invalid option. Usage: $0 {listDevices|numDevices|hasDiscrete|discreteUUID|discreteName|discreteIndex|hasIntegrated|integratedUUID|integratedName|integratedIndex|hasVulkan|vulkanVersion}"
        exit 1
        ;;
esac
