#!/bin/dash

# Set initial hostname for connman DHCP request.
# If DHCP provides a hostname, connman will set it.
# Later, S26system resets to system.hostname if it's non-empty or else keep DHCP hostname.

# configure wifi files
system_wifi_configure() {
    case "$1" in
        1) settings_name="default"; settings_hide=false ;;
        .hidden) settings_name="hidden_AP"; settings_hide=true; X="$1" ;;
        *) settings_name="$1"; settings_hide=false; X="$1" ;;
    esac
    settings_ssid="$(/usr/bin/regmsg systemconf getconfigkey "wifi${X}.ssid")"
    settings_key="$(/usr/bin/regmsg systemconf getconfigkey "wifi${X}.key")"
    settings_file="/var/lib/connman/system_wifi${X}.config"
    { [ -n "$settings_key" ] && optionalPassphrase="Passphrase=${settings_key}"; } || unset optionalPassphrase

    # Create or remove wifi configuration files based on SSID
    if [ -n "$settings_ssid" ]; then
        {
        printf '%s\n' \
            "[global]" \
            "Name=system" \
            "[service_system_${settings_name}]" \
            "Type=wifi" \
            "Name=${settings_ssid}" \
            "Hidden=${settings_hide}"
        [ -n "$optionalPassphrase" ] && printf '%s\n' "$optionalPassphrase"
        printf '%s\n' "Autoconnect=true"
        } > "$settings_file"
    else
        rm -f "${settings_file}"
    fi
}

wifi_enable() {
    wifi_country="$(/usr/bin/regmsg systemconf getconfigkey wifi.country)"
    [ -n "$wifi_country" ] && /usr/sbin/iw reg set "$wifi_country"
    /usr/bin/regmsg wifi enable
    /usr/bin/regmsg wifi scan
} 2>/dev/null

start() {
    system_hostname="$(/usr/bin/regmsg systemconf getconfigkey system.hostname)"
    [ -n "$system_hostname" ] && hostname "$system_hostname"

    wifi_enabled="$(/usr/bin/regmsg systemconf getconfigkey wifi.enabled)"
    if [ "$wifi_enabled" = "1" ]; then
        for i in 1 2 3 .hidden; do
            system_wifi_configure "$i"
        done
    fi
    printf "Starting connman: "
    start-stop-daemon -S -q -m -b -p /var/run/connmand.pid --exec /usr/sbin/connmand -- -n -r

    i=1    # Wait for connmand to be ready (max 5 seconds)
    while [ $i -le 20 ]; do
        if connmanctl state 2>/dev/null | grep -qE '^[[:space:]]*State[[:space:]]*='; then
            break
        fi
        sleep 0.25
        i=$((i + 1))
    done

    if [ "$wifi_enabled" = "1" ]; then
        wifi_enable &
    else
        /usr/bin/regmsg wifi disable 2>/dev/null &
    fi
    echo "done."
}

stop() {
    printf "Stopping connman: "
    start-stop-daemon -K -q --oknodo --remove-pidfile -p /var/run/connmand.pid
    echo "done."
}

case "$1" in
    start) start ;;
    stop)  stop ;;
    restart|reload)
        stop
        sleep 0.5
        start
        ;;
    *) echo "usage: $0 {start|stop|restart|reload}" >&2 ;;
esac
