#!/bin/dash

reg_xarcade2jstick() {
    if ! /usr/bin/xarcade2jstick -d >/dev/null 2>&1; then
        for dev in /usr/share/reglinux/datainit/system/configs/xarcade2jstick/*; do
            [ -e "$dev" ] || continue
            devname=$(basename "$dev")
            [ -h "/dev/input/by-id/$devname" ] && /usr/bin/xarcade2jstick -d -e "/dev/input/by-id/$devname" >/dev/null 2>&1 && break
        done
    fi
}

reg_hostname() {
    current_hostname=$(hostname)
    if [ -n "$current_hostname" ]; then
        echo "Creating /etc/hosts"
        printf '%s\t%s\n' "127.0.0.1" "localhost" > /etc/hosts
        printf '%s\t%s\n' "127.0.1.1" "$current_hostname" >> /etc/hosts
    fi
}

case "$1" in
  start)
    # Run async tasks in background
    printf "Starting system: "
    system_kblayout="$(/usr/bin/regmsg systemconf getconfigkey system.kblayout)"; loadkeys "${system_kblayout:-us}" &
    system_timezone="$(/usr/bin/regmsg systemconf getconfigkey system.timezone)"; [ -n "$system_timezone" ] && { /usr/bin/system-config tz "$system_timezone" & }
    [ "$(/usr/bin/regmsg systemconf getconfigkey controllers.xarcade.enabled)" = "1" ] && { reg_xarcade2jstick & }
    reg_hostname &
    echo '/userdata/system/logs/core.%e' > /proc/sys/kernel/core_pattern
    wait    # Wait for all background jobs
    echo "done."
    ;;
  stop|restart|reload)
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|reload}" >&2
    exit 1
    ;;
esac