#!/bin/dash
[ "$1" != "start" ] && exit 0

#             keycode 59 = F1  F13  Console_13      
#         alt keycode 59 = Console_1       # disable these lines
# control alt keycode 59 = Console_1  
dumpkeys | grep -vE '^[[:space:]]*alt[[:space:]]+keycode[[:space:]]+[0-9]+[[:space:]]*=[[:space:]]*Console_[0-9]+[[:space:]]*$' | loadkeys &
