#!/bin/sh
#
# Make system.conf specific values available to system-boot.conf
# in a very early boot stage process where the regular conf-file
# is not available.

# Only copy values on shutdown/reboot
[ "$1" = "stop" ] || exit 0

set --
for key in wifi.enabled wifi.ssid wifi.key wifi2.ssid wifi2.key wifi3.ssid wifi3.key wifi.hidden.ssid wifi.hidden.key system.timezone es.resolution system.hostname
do
    value="$(/usr/bin/system-settings-get "$key")" # in case it is empty, it must be set in the system-boot.conf file to erase any existing value
    if [ "$value" != "$(/usr/bin/system-settings-get -f /boot/system-boot.conf "$key")" ]
    then
        set -- "$@" "$key" "$value"
    fi
done

if [ $# -gt 0 ]
then
    mount -o remount,rw /boot
    /usr/bin/system-settings-set -f /boot/system-boot.conf "$@"
    mount -o remount,ro /boot
fi

exit $?
