#!/bin/dash
get_key() {
    /usr/bin/regmsg systemconf getconfigkey "$1" 2>/dev/null || awk -F'=' -v k="$1" '$0 !~ /^[[:space:]]*#/ && $1 == k {print $2; exit}' /boot/system-boot.conf 2>/dev/null
}
usbmode=$(get_key system.usb.mode)

case "$1" in
    enable|enabled)
        /usr/bin/regmsg systemconf setconfigkey /userdata/system/system.conf system.usb.mode adb
        exit 0
        ;;
    disable|disabled)
        # Only disable if currently in adb mode, otherwise we might be overriding mtp.
        [ "$usbmode" = "adb" ] && /usr/bin/regmsg systemconf setconfigkey /userdata/system/system.conf system.usb.mode off
        exit 0
        ;;
    status)
        { [ "$usbmode" = "adb" ] && printf 'ADB status: enabled\n'; } || printf 'ADB status: disabled\n'
        ;;
esac

[ "$usbmode" = "adb" ] || exit 0

case "$1" in
    start)
        /usr/bin/usbgadget adb
        ;;
    stop)
        /usr/bin/usbgadget stop
        ;;
    restart|reload)
        /usr/bin/usbgadget stop
        /usr/bin/usbgadget adb
        ;;
    *)
        printf '%s\n' "Usage: $0 {start|stop|restart|enable|disable|status}" >&2
        exit 1
        ;;
esac
