#!/bin/bash
case "$1" in
  start|stop|restart|reload)
    ;;
  status)
    [ "$(/usr/bin/system-settings-get system.samba.enabled)" = "0" ] && echo "SAMBA status: disabled" || echo "SAMBA status: enabled"
    ;;
  enabled)
      /usr/bin/system-settings-set system.samba.enabled 1
      /etc/init.d/S91smbd start
      /etc/init.d/S93wsdd start
    ;;
  disabled)
      /etc/init.d/S91smbd stop
      /etc/init.d/S93wsdd stop
      /usr/bin/system-settings-set system.samba.enabled 0
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|reload|enabled|disabled|status}"
    exit 1
esac