#!/bin/dash
[ "$(/usr/bin/regmsg systemconf getConfigKey system.samba.enabled)" = "0" ] && { printf '%s\n' "SMB services: disabled"; exit 0; }

start() {
    { [ "$(/usr/bin/regmsg systemconf getConfigKey system.security.enabled)" = "0" ] && CONFIGFILE="/etc/ksmbd/ksmbd.conf"; } || CONFIGFILE="/etc/ksmbd/ksmbd-secure.conf"

    printf 'Starting SMB services: '
    if modprobe ksmbd && ksmbd.mountd --config="$CONFIGFILE" && touch /var/lock/subsys/smb 2>/dev/null; then
        printf 'done\n'
        return 0
    else
        printf 'failed\n'
        return 1
    fi
}

stop() {
    printf 'Shutting down SMB services: '
    if ksmbd.control -s && rmmod ksmbd && rm -f /var/lock/subsys/smb; then
        printf 'done\n'
        return 0
    else
        printf 'failed\n'
        return 1
    fi
}

reload() {
    printf 'Reloading smb.conf file: '
    if ksmbd.control -r; then
        printf 'done\n'
        return 0
    else
        printf 'failed\n'
        return 1
    fi
}

case "$1" in
    start)   start ;;
    stop)    stop  ;;
    restart) stop ; start ;;
    reload)  reload ;;
    *)
        printf 'Usage: %s {start|stop|restart|reload}\n' "${0##*/}" >&2
        exit 1
esac