#!/bin/bash
#
# Stolen from RedHat FC5.

if [ "$(/usr/bin/system-settings-get system.samba.enabled)" = "0" ]; then
    echo "SMB services: disabled"
    exit 0
fi

start() {
    if [ "$(/usr/bin/system-settings-get system.security.enabled)" = "1" ]; then
        CONFIGFILE="/etc/samba/smb-secure.conf"
    else
        CONFIGFILE="/etc/samba/smb.conf"
    fi
    # Make directories.
    mkdir -p /var/cache/samba /var/log/samba /var/lock/subsys /var/run/samba

    echo -n "Starting SMB services: "
    if smbd -D --configfile="${CONFIGFILE}"; then
        echo "done"
        echo -n "Starting NMB services: "
        if nmbd -D --configfile="${CONFIGFILE}"; then
            echo "done"
            touch /var/lock/subsys/smb
            return 0
        fi
     fi
     echo "failed"
     return 1
}

stop() {
    echo -n "Shutting down SMB services: "
    sync
    if kill -15 "$(pidof smbd)"; then
        rm -f /var/run/samba/smbd.pid
        echo "done"
        echo -n "Shutting down NMB services: "
        if kill -15 "$(pidof nmbd)"; then
            rm -f /var/run/samba/nmbd.pid
            rm -f /var/lock/subsys/smb
            echo "done"
            return 0
        fi
     fi
     echo "failed"
     return 1
}

reload() {
    echo -n "Reloading smb.conf file: "
    smbcontrol smbd reload-config && echo "done" && return 0
    echo "failed"
    return 1
}

case "$1" in
  start)
      start
    ;;
  stop)
      stop
    ;;
  restart)
      stop
      start
    ;;
  reload)
      reload
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|reload}"
    exit 1
esac

exit $?
