default:
  options:
    gfxbackend: gl
    video_threaded: true
    smooth: false
    retroarch.menu_driver: ozone
    retroarch.menu_scale_factor: "1.500000"
    retroarch.audio_driver: alsathread

nds:
  emulator: libretro
  core:     melonds

dreamcast:
  emulator: libretro
  core:     flycast

n64:
  emulator: libretro
  core:     parallel_n64
