default:
  options:
    videomode: max-1280x720

nds:
  emulator: drastic
  core:     drastic
fmtowns:
  emulator: libretro
  core:     mame
psx:
  options:
    gpu_software: true
    gfxbackend: Software
atomiswave:
  emulator: libretro
  core:     morpheuscast-xtreme
dreamcast:
  emulator: libretro
  core:     morpheuscast-xtreme
naomi:
  emulator: libretro
  core:     morpheuscast-xtreme
flash:
  emulator: lightspark
  core:     lightspark
