default:
  options:
    retroarch.menu_driver: rgui

nds:
  emulator: drastic
  core:     drastic
fmtowns:
  emulator: libretro
  core:     mame
atomiswave:
  emulator: libretro
  core:     morpheuscast-xtreme
dreamcast:
  emulator: libretro
  core:     morpheuscast-xtreme
naomi:
  emulator: libretro
  core:     morpheuscast-xtreme
