#!/bin/dash

start() {
    SYNCTHING_CONFIG="/userdata/system/configs/syncthing/"
    SYNCTHING_LOG="/userdata/system/logs/syncthing.log"

    # check if syncthing web ui should be accessible from outside (default is "no")
    { [ "$(/usr/bin/regmsg systemconf getconfigkey system.security.enabled)"  = "0" ] && SYNCTHING_GUI="http://0.0.0.0:8384"; } || SYNCTHING_GUI="http://127.0.0.1:8384"

    # create config directory if not present
    [ -d $SYNCTHING_CONFIG ] || mkdir /userdata/system/configs/syncthing/
    
    printf "Starting syncthing service: "
    { start-stop-daemon -S -b -q -x /usr/bin/syncthing -- serve --no-upgrade --no-browser --logflags=2 --logfile="$SYNCTHING_LOG" --home="$SYNCTHING_CONFIG" --gui-address="$SYNCTHING_GUI" && echo "done"; } || { echo FAIL; exit 1; }
}

stop() {
    printf "Shutting down syncthing service: "
    { start-stop-daemon -K -q -n syncthing && echo "done"; } || { echo FAIL; exit 1; }
}

restart() {
    stop
    start
}

reload() {
    printf "Reloading syncthing service: "
    { kill -HUP $(pidof syncthing) && echo "done"; } || { echo FAIL; exit 1; }
}

case "$1" in
    start)   start   ;;
    stop)    stop    ;;
    restart) restart ;;
    reload)  reload  ;;
    *)
        echo "Usage: $0 {start|stop|restart|reload}"
        exit 1
esac