#!/bin/sh

CONFIGFILE=/boot/config.txt

f_usage() {
    echo "Uso: ${0} [gpicase|gpicase2|gpicase2w]" >&2
    echo "  gpicase   - Configures for the GPi Case." >&2
    echo "  gpicase2  - Configures for the GPi Case 2." >&2
    echo "  gpicase2w - Configures for the GPi Case 2W." >&2
}

do_config() {
    setup="# ====== GPi Case setup section =====
    ${video}
    dtparam=act_led_trigger=none
    dtparam=act_led_activelow=on
    # ====== GPi Case setup section end ====="

    mount -o remount,rw /boot
    echo "${setup}" | sed -i '/# ====== GPi Case setup section =====/,/# ====== GPi Case setup section end =====/d' "${CONFIGFILE}"
    echo "${setup}" >> "${CONFIGFILE}"
    mount -o remount,ro /boot
    >&2 echo "${ACTION} support installed!"
    >&2 echo "Please reboot the system so that the changes take effect!"
}

if [ $# -ne 1 ]; then
    f_usage
    exit 1
fi

trap 'mount -o remount,ro /boot' EXIT

ACTION=$1

case "${ACTION}" in
"gpicase")
    video="dtoverlay=retroflag-gpicase"
    /usr/bin/system-settings-set system.es.environment wayland
    do_config
    ;;
"gpicase2")
    video="dtoverlay=retroflag-gpicase2"
    do_config
    ;;
"gpicase2w")
    video="dtoverlay=retroflag-gpicase2w"
    do_config
    ;;
*)
    f_usage
    >&2 echo "Error: Invalid command '${ACTION}'. Use one of the following: gpicase, gpicase2, gpicase2w."
    exit 1
    ;;
esac

exit 0
