default:
  options:
    video_threaded: true
    smooth: false
    retroarch.menu_driver: xmb
    retroarch.audio_driver: alsathread

mastersystem:
  emulator: libretro
  core:     picodrive
megadrive:
  emulator: libretro
  core:     picodrive
snes:
  emulator: libretro
  core:     snes9x
c64:
  emulator: libretro
  core:     vice_x64
c20:
  emulator: libretro
  core:     vice_xvic
c128:
  emulator: libretro
  core:     vice_x128
cplus4:
  emulator: libretro
  core:     vice_xplus4
pet:
  emulator: libretro
  core:     vice_xpet
fbneo:
  options:
    frameskip: auto
flash:
  emulator: lightspark
  core:     lightspark

