default:
  options:
    hud_support: true

nds:
  emulator: drastic
  core:     drastic
flash:
  emulator: lightspark
  core:     lightspark
fmtowns:
  emulator: libretro
  core:     mame
model3:
  emulator: supermodel
  core:     supermodel-legacy
  options:
    videomode: max-720x576
scummvm:
  emulator: scummvm
  core:     scummvm
quake3:
  emulator: ioquake3
  core:     ioquake3
  options:
    videomode: max-1280x720
jaguar:
  emulator: bigpemu
  core:     bigpemu
