default:
  options:
    video_threaded: true
    videomode: max-1280x720
    retroarch.audio_driver: alsathread
    # menu retroarch
    retroarch.menu_driver:  xmb

amiga500:
  emulator: amiberry
  core:     A500
amiga1200:
  emulator: amiberry
  core:     A1200
amigacd32:
  emulator: amiberry
  core:     CD32
mastersystem:
  emulator: libretro
  core:     picodrive
megadrive:
  emulator: libretro
  core:     picodrive
snes:
  emulator: libretro
  core:     snes9x
c64:
  emulator: vice
  core:     x64
c128:
  emulator: vice
  core:     x128
c20:
  emulator: vice
  core:     xvic
pet:
  emulator: vice
  core:     xpet
cplus4:
  emulator: vice
  core:     xplus4
fbneo:
  options:
    frameskip: auto
flash:
  emulator: lightspark
  core:     lightspark

