default:
  options:
    hud_support: true
    video_frame_delay_auto: true

pcengine:
  emulator: libretro
  core:     pce
pcenginecd:
  emulator: libretro
  core:     pce
saturn:
  emulator: libretro
  core:     beetle-saturn
cdi:
  emulator: libretro
  core:     same_cdi
