default:
  options:
    video_threaded: true

amiga500:
  emulator: libretro
  core:     puae
amiga1200:
  emulator: libretro
  core:     puae
amigacd32:
  emulator: libretro
  core:     puae
atari2600:
  emulator: libretro
  core:     stella2014
mastersystem:
  emulator: libretro
  core:     picodrive
megadrive:
  emulator: libretro
  core:     picodrive
snes:
  emulator: libretro
  core:     snes9x
c64:
  emulator: vice
  core:     x64
c128:
  emulator: vice
  core:     x128
c20:
  emulator: vice
  core:     xvic
pet:
  emulator: vice
  core:     xpet
cplus4:
  emulator: vice
  core:     xplus4
fbneo:
  options:
    frameskip: auto
flash:
  emulator: lightspark
  core:     lightspark

