default:
  options:
    video_threaded: true
    smooth: false
    retroarch.menu_driver: xmb
    retroarch.audio_driver: alsathread

nds:
  emulator: libretro
  core:     melonds
fmtowns:
  emulator: libretro
  core:     mame
flash:
  emulator: lightspark
  core:     lightspark

