default:
  options:
    videomode: max-1280x720
    video_threaded: true
    smooth: false
    retroarch.menu_driver: xmb
    retroarch.audio_driver: alsathread

nds:
  emulator: drastic
  core:     drastic
fmtowns:
  emulator: libretro
  core:     mame
psx:
  options:
    gpu_software: true
    gfxbackend: Software
atomiswave:
  emulator: libretro
  core:     flycastvl
dreamcast:
  emulator: libretro
  core:     flycastvl
naomi:
  emulator: libretro
  core:     flycastvl
flash:
  emulator: lightspark
  core:     lightspark
c64:
  emulator: libretro
  core:     vice_x64
c20:
  emulator: libretro
  core:     vice_xvic
c128:
  emulator: libretro
  core:     vice_x128
cplus4:
  emulator: libretro
  core:     vice_xplus4
pet:
  emulator: libretro
  core:     vice_xpet
