#!/bin/bash
#
# KSMBD network share script

if [ "$(/usr/bin/system-settings-get system.samba.enabled)" = "0" ]; then
    echo "SMB services: disabled"
    exit 0
fi

start() {
    if [ "$(/usr/bin/system-settings-get system.security.enabled)" = "1" ]; then
        CONFIGFILE="/etc/ksmbd/ksmbd-secure.conf"
    else
        CONFIGFILE="/etc/ksmbd/ksmbd.conf"
    fi

    echo -n "Starting SMB services: "
    modprobe ksmbd && ksmbd.mountd --config="$CONFIGFILE" && touch /var/lock/subsys/smb && echo "done" && return 0
    echo "failed"
    return 1
}

stop() {
    echo -n "Shutting down SMB services: "
    ksmbd.control -s && rmmod ksmbd && rm -f /var/lock/subsys/smb && echo "done" && return 0
    echo "failed"
    return 1
}

reload() {
    echo -n "Reloading smb.conf file: "
    if ksmbd.control -r; then
        echo "done"
        return 0
    else
        echo "failed"
        return 1
    fi
}

case "$1" in
  start)
      start
    ;;
  stop)
      stop
    ;;
  restart)
      stop
      start
    ;;
  reload)
      reload
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|reload}"
    exit 1
esac

exit $?
