#!/bin/dash
#
# S93wsdd - init.d script for WSDD on REG-Linux
# "I haven't written a straight init.d script in 2 decades" Edition
# (c) 2023 Jay Moore - dewdude@pickmy.org - Now With More Gross Hacks!
# Distributed under the terms of the MIT license
#
# Modified by n2qz and other Batocera contributors, for inclusion in Batocera.
# Modified by Romain Tisserand for REG Linux
# Optimized for dash shell by Carlos Martins

DAEMON=/usr/bin/wsdd
if [ "$(/usr/bin/regmsg getConfigKey system.samba.enabled)" = "0" ] || [ ! -x "$DAEMON" ]; then
    printf '%s: disabled\n' "SMB services ($0)" >&2
    exit 0
fi

PATH=/sbin:/usr/sbin:/bin:/usr/bin
NAME=wsdd
PIDFILE=/var/run/wsdd.pid
LOG_FILE=/userdata/system/logs/wsdd.log

do_start() {
    printf 'Starting %s:\n' "$NAME"
    { [ "$(/usr/bin/regmsg getConfigKey system.security.enabled)" = "0" ] && SMB_CONFIG_FILE="/etc/ksmbd/ksmbd.conf"; } || SMB_CONFIG_FILE="/etc/ksmbd/ksmbd-secure.conf"
    # wssd-native needs to be run as unix daemon, and needs username (we're using root)
    OPTS="--unixd -U root --log-file $LOG_FILE --smb-conf $SMB_CONFIG_FILE"
    start-stop-daemon --start --background --make-pidfile --pidfile "${PIDFILE}" --exec "${DAEMON}" -- ${OPTS}
    printf 'done\n'
}

do_stop() {
    printf 'Stopping %s:\n' "$NAME"
    start-stop-daemon -K -q -R 2 -n "$NAME" && rm -f "${PIDFILE}"
    printf 'done\n'
}

case "$1" in
    start) do_start ;;
    stop)  do_stop  ;;
    restart|force-reload)
        printf 'Restarting %s:\n' "$NAME"
        do_stop
        do_start
        ;;
    *)
        printf 'Usage: %s {start|stop|restart|force-reload}\n' "${0##*/}" >&2
        exit 3
        ;;
esac


#MIT License
#Copyright (c) 2023 Jay Moore
#
#Permission is hereby granted, free of charge, to any person obtaining a copy
#of this software and associated documentation files (the "Software"), to deal
#in the Software without restriction, including without limitation the rights
#to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#copies of the Software, and to permit persons to whom the Software is
#furnished to do so, subject to the following conditions:
#
#The above copyright notice and this permission notice shall be included in all
#copies or substantial portions of the Software.
#
#THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#SOFTWARE.
