#!/bin/bash
#
# S93wsdd - init.d script for WSDD on REG-Linux
# "I haven't written a straight init.d script in 2 decades" Edition
# (c) 2023 Jay Moore - dewdude@pickmy.org - Now With More Gross Hacks!
# Distributed under the terms of the MIT license
#
# Modified by n2qz and other Batocera contributors, for inclusion in
# Batocera.
# Modified by Romain Tisserand for REG Linux

PATH=/sbin:/usr/sbin:/bin:/usr/bin
DESC="wsdd"
NAME=wsdd
DAEMON=/usr/bin/wsdd
PIDFILE=/var/run/wsdd.pid
LOG_FILE=/userdata/system/logs/wsdd.log

if [ "$(/usr/bin/system-settings-get system.samba.enabled)" = "0" ] || [ ! -x "$DAEMON" ]; then
    echo "SMB services ( $0 ): disabled"
    exit 0
fi

# Function that starts the daemon/service
do_start() {
    if [ "$(/usr/bin/system-settings-get system.security.enabled)" = "1" ]; then
        SMB_CONFIG_FILE="/etc/ksmbd/ksmbd-secure.conf"
    else
        SMB_CONFIG_FILE="/etc/ksmbd/ksmbd.conf"
    fi

    # wssd-native requires username, use root
    OPTS="-U root"
    # wssd-native needs to be run as unix daemon
    OPTS="--unixd ${OPTS}"
    # location of samba.conf workgroup etc. information from
    OPTS="${OPTS} --log-file ${LOG_FILE} --smb-conf ${SMB_CONFIG_FILE}"

    start-stop-daemon --start --background --make-pidfile --pidfile "${PIDFILE}" --exec "${DAEMON}" -- ${OPTS}
}

# Function that stops the daemon/service
do_stop() {
    start-stop-daemon --stop --remove-pidfile --pidfile "${PIDFILE}"
}

case "$1" in
    start)
        echo "Starting $DESC: $NAME"
        do_start
        RETVAL=$?
        echo done
        exit $RETVAL
        ;;
    stop)
        echo "Stopping $DESC: $NAME"
        do_stop
        RETVAL=$?
        echo done
        exit $RETVAL
        ;;
    restart|force-reload)
        echo "Restarting $DESC: $NAME"
        do_stop
        sleep 1
        do_start
        RETVAL=$?
        echo done
        exit $RETVAL
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|force-reload}" >&2
        exit 3
        ;;
esac


#MIT License
#Copyright (c) 2023 Jay Moore
#
#Permission is hereby granted, free of charge, to any person obtaining a copy
#of this software and associated documentation files (the "Software"), to deal
#in the Software without restriction, including without limitation the rights
#to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#copies of the Software, and to permit persons to whom the Software is
#furnished to do so, subject to the following conditions:
#
#The above copyright notice and this permission notice shall be included in all
#copies or substantial portions of the Software.
#
#THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#SOFTWARE.
