KEY_VOLUMEUP 1               /usr/bin/volume-button volup
KEY_VOLUMEDOWN 1             /usr/bin/volume-button voldown
KEY_VOLUMEUP 0               /usr/bin/volume-button-release
KEY_VOLUMEDOWN 0             /usr/bin/volume-button-release
KEY_VOLUMEUP+BTN_MODE 1      /usr/bin/volume-button briup
KEY_VOLUMEDOWN+BTN_MODE 1    /usr/bin/volume-button bridown
KEY_VOLUMEUP+BTN_MODE 0      /usr/bin/volume-button-release
KEY_VOLUMEDOWN+BTN_MODE 0    /usr/bin/volume-button-release
KEY_POWER+BTN_MODE 1         /usr/bin/poweroff.sh
KEY_POWER 1                  /usr/bin/power-button
KEY_POWER 0                  /usr/bin/power-button-release
BTN_START+BTN_SELECT 1       batocera-screenshot
BTN_SELECT+BTN_MODE 1        /usr/bin/dpad-toggle
SW_TABLET_MODE 1             /usr/bin/toggle-switch enable
SW_TABLET_MODE 0             /usr/bin/toggle-switch disable
SW_HEADPHONE_INSERT 1        /usr/bin/trimui-volume-attenuate headphone
SW_HEADPHONE_INSERT 0        /usr/bin/trimui-volume-attenuate speaker
BTN_START+BTN_MODE+ 1        /usr/bin/knulli-softreset
