#!/bin/sh

if test "$1" != "start"; then
    exit 0
fi

mkdir -p "/var/log"
log="/var/log/nvidia.log"

echo  > $log
echo "OS version: $(system-version)" >> $log
echo  >> $log

# detect the appropriate Nvidia driver
if grep -qE "^[ ]*nvidia-driver[ ]*=[ ]*true[ ]*$" /boot/system-boot.conf
then
    echo "Manual setting to latest production driver" >> $log
    batocera-nvidia production
elif grep -qE "^[ ]*nvidia-driver[ ]*=[ ]*legacy[ ]*$" /boot/system-boot.conf
then
    echo "Manual setting to legacy 470 driver" >> $log
    batocera-nvidia legacy
elif grep -qE "^[ ]*nvidia-driver[ ]*=[ ]*legacy390[ ]*$" /boot/system-boot.conf
then
    echo "Manual setting to legacy 390 driver" >> $log
    batocera-nvidia legacy390
elif grep -qE "^[ ]*nvidia-driver[ ]*=[ ]*legacy340[ ]*$" /boot/system-boot.conf
then
    echo "Manual setting to legacy 340 driver, however it's broken, using nouveau" >> $log
    batocera-nvidia nouveau
elif grep -qE "^[ ]*nvidia-driver[ ]*=[ ]*false[ ]*$" /boot/system-boot.conf
then
    echo "Manual setting to nouveau driver" >> $log
    batocera-nvidia nouveau
else
    echo "Using automatic Nvidia driver detection" >> $log
    batocera-nvidia auto
fi
