from pathlib import Path
from typing import Any

from configgen.systemFiles import CONF, LOGDIR
from configgen.utils.logger import get_logger

GZDOOM_CONFIG_DIR = str(Path(CONF) / "gzdoom")
GZDOOM_CONFIG_PATH = str(Path(GZDOOM_CONFIG_DIR) / "gzdoom.ini")
GZDOOM_LOG_PATH = str(Path(LOGDIR) / "gzdoom.log")
GZDOOM_SCRIPT_PATH = str(Path(GZDOOM_CONFIG_DIR) / "gzdoom.cfg")
GZDOOM_SOUND_FONT_PATH = str(Path(GZDOOM_CONFIG_DIR) / "soundfonts")
GZDOOM_FM_BANKS_PATH = str(Path(GZDOOM_CONFIG_DIR) / "fm_banks")
GZDOOM_ARCH_PATH = "/usr/share/reglinux/system.arch"


eslog = get_logger(__name__)


def setGzdoomConfig(system: Any, rom: str) -> None:
    gzdoom_api = system.config["gz_api"] if system.isOptSet("gz_api") else "0"

    # RPi4 workaround which has both ligl & libgles
    # For arm systems, we want to force OpenGL ES - 3
    if gzdoom_api == "0":
        with Path(GZDOOM_ARCH_PATH).open() as file:
            content = file.read().strip()
            if content not in ("x86_64", "x86_64_v3"):
                gzdoom_api = "3"

    # now set the config
    extra_config = ""
    if gzdoom_api == "3":
        extra_config = (
            "gl_es 1\n"
            "vid_preferbackend 3\n"
            # This setting greatly improves performance:
            "gles_use_mapped_buffer true\n"
        )
    else:
        extra_config = f"vid_preferbackend {gzdoom_api}\n"

    # A script file with console commands that are always ran when a game starts
    with Path(GZDOOM_SCRIPT_PATH).open("w") as script:
        script.write(
            "# This file is automatically generated by gzdoomGenerator.py\n"
            # In the code, logfile does not appear to be created unless done so explicitly
            f"logfile {GZDOOM_LOG_PATH}\n"
            f"vid_fps {'true' if system.getOptBoolean('showFPS') else 'false'}\n"
            f"{extra_config}"
            "echo REG-Linux\n",  # easy check that script ran in console
        )

    # check the directory name is in the ini file
    if not Path(GZDOOM_CONFIG_PATH).exists():
        Path(GZDOOM_CONFIG_PATH).write_text(
            "[IWADSearch.Directories]\n"
            "Path=/userdata/roms/gzdoom\n"
            "[FileSearch.Directories]\n"
            "Path=/userdata/roms/gzdoom\n"
            "[SoundfontSearch.Directories]\n"
            "Path=" + GZDOOM_SOUND_FONT_PATH + "\n"
            "Path=" + GZDOOM_FM_BANKS_PATH + "\n"
            "[GlobalSettings]\n"
        )
    else:
        # configparser wasn't working on the default ini file (non-compliant)
        # it's not a true ini file, use this crude method instead
        line_to_add = "Path=" + str(Path(rom).parent) + "\n"
        with Path(GZDOOM_CONFIG_PATH).open() as file:
            lines = file.readlines()
            if line_to_add not in lines:
                for i in range(len(lines)):
                    if lines[i] == "[IWADSearch.Directories]\n":
                        lines.insert(i + 1, line_to_add)
                    if lines[i] == "[FileSearch.Directories]\n":
                        lines.insert(i + 1, line_to_add)

        with Path(GZDOOM_CONFIG_PATH).open("w") as file:
            file.writelines(lines)

    # also check the config directories are also set
    with Path(GZDOOM_CONFIG_PATH).open() as file:
        lines = file.readlines()
        if GZDOOM_FM_BANKS_PATH not in lines:
            for i in range(len(lines)):
                if lines[i] == "[SoundfontSearch.Directories]\n":
                    lines.insert(i + 1, GZDOOM_FM_BANKS_PATH)

        if GZDOOM_SOUND_FONT_PATH not in lines:
            for i in range(len(lines)):
                if lines[i] == "[SoundfontSearch.Directories]\n":
                    lines.insert(i + 1, GZDOOM_SOUND_FONT_PATH)

    with Path(GZDOOM_CONFIG_PATH).open("w") as file:
        file.writelines(lines)
