#!/bin/dash
# Starts audio services

case "$1" in
	start)	printf 'Starting alsa: OK\n' ;;
	stop)
		printf 'Stopping alsa: '
		{ mount -o remount,rw /boot 2>/dev/null && alsactl store -f /boot/asound.state 2>/dev/null; } || { printf 'error writing to /boot.\n' >&2; exit 1; }
		{ [ -f /userdata/system/.asoundrc ] && cp /userdata/system/.asoundrc /boot/asoundrc; } || rm -f /boot/asoundrc
		mount -o remount,ro /boot 2>/dev/null || { printf 'error remounting /boot.\n' >&2; exit 1; }
		printf 'OK\n'
		;;
	restart|reload)
		"$0" stop && exec "$0" start
		;;
	*)
		printf 'Usage: %s {start|stop|restart}\n' "$0" >&2
		exit 1
		;;
esac
