#!/bin/dash

# Redirect output to log
exec >>/userdata/system/logs/emulationstation.log 2>&1

case "$1" in
start)
    . /etc/profile.d/xdg.sh
    . /etc/profile.d/dbus.sh

    resolution="$(/usr/bin/regmsg screen getresolution)"
    if [ "${resolution%x*}" -gt "${resolution#*x}" ]; then
            /usr/bin/plymouth change-mode --reboot
            /usr/bin/plymouth quit --retain-splash
    else
            # Temporarily move header image to avoid rotated splash screen in some devices
            mv /usr/share/plymouth/themes/reglinux/images/header-image.png /usr/share/plymouth/themes/reglinux/images/header-image.png.bak
            /usr/bin/plymouth change-mode --reboot
            /usr/bin/plymouth quit --retain-splash
            mv /usr/share/plymouth/themes/reglinux/images/header-image.png.bak /usr/share/plymouth/themes/reglinux/images/header-image.png
    fi

    if [ "$(/usr/bin/regmsg systemconf getconfigkey system.es.atstartup)" != "0" ]; then
        if [ "$XDG_SESSION_TYPE" = "wayland" ]; then
            WLR_LIBINPUT_NO_DEVICES=1 /usr/bin/sway &
        else
            %REGSTATION_CMD% %REGSTATION_POSTFIX%
        fi
    fi
    ;;
stop)
    emulationstation-standalone --stop-rebooting
    pkill -f sway
    pkill -f regstation

    i=0 # Wait up to 5 seconds for regstation to exit
    while pgrep -f regstation >/dev/null ; do
        [ $i -gt 20 ] && break
        sleep 0.25
        i=$((i + 1))
    done
    # Change scren to "GAME OVER"
    /usr/sbin/plymouthd --mode=shutdown --graphical-boot --attach-to-session && /usr/bin/plymouth --show-splash
    ;;
restart|reload)
    "$0" stop
    "$0" start
    ;;
*)
    exec echo "Usage: $0 {start|stop|restart}"
    exit 1
    ;;
esac
