#!/bin/dash

do_help() {
    echo "Usage: $0 {scanlist|list|start|enable [ssid] [key]|disable}" >&2
}

do_list() {
    # remove duplicates and hidden networks (those without SSID)
    connmanctl services | awk '
        /^... / {
            sub(/^...[ \t]*/, "")
            line = $0
            
            # Skip if it looks like a hidden network identifier
            if (line ~ /^wifi_[[:alnum:]]+_/) next
            
            # Handle networks with interface identifiers in the name
            if (match(line, /[ \t]wifi_[[:alnum:]]+_([^\t ]+)/, arr)) {
                name = substr(line, 1, RSTART - 1)
                gsub(/^[ \t]+|[ \t]+$/, "", name)
                if (name != "" && !seen[name]++) print name
            } else if (!seen[line]++) {
                print line
            }
        }
    '
}

do_scanlist() {
    connmanctl scan wifi >/dev/null 2>&1
    do_list
}

wait_for_ip() {
    mode="$1"
    i=0
    while [ "$i" -lt 20 ]; do
        case "$mode" in
            up)
                # Check for any non-loopback IPv4 address
                ip -4 addr show scope global | grep -q 'inet ' && return 0
                ;;
            down)
                # Ensure no non-loopback IPv4 address exists
                ip -4 addr show scope global | grep -q 'inet ' || return 0
                ;;
        esac
        sleep 0.5
        i=$((i + 1))
    done
}

if [ $# -eq 0 ]; then
    do_help
    exit 1
fi

ACTION=$1
shift

case "${ACTION}" in
    list) do_list ;;
    scanlist) do_scanlist ;;
    start) exec /etc/init.d/S08connman restart ;;
    enable)
        { [ "$#" -eq 2 ] && /usr/bin/regmsg systemconf setconfigkey /userdata/system/system.conf wifi.enabled 1 wifi.ssid "$1" wifi.key "$2"; } || /usr/bin/regmsg systemconf setconfigkey /userdata/system/system.conf wifi.enabled 1
        /etc/init.d/S08connman reload

        # Wait for an IP only if there is a saved ssid
        if [ -n "$(/usr/bin/regmsg systemconf getconfigkey wifi.ssid)" ]; then
            sleep 1                     # wait 1 second for connman to initialize and start scanning
            wait_for_ip up
        fi
        ;;
    disable)
        /usr/bin/regmsg systemconf setconfigkey /userdata/system/system.conf wifi.enabled 0
        /etc/init.d/S08connman reload
        wait_for_ip down
        ;;
    *)
        do_help
        echo "error: invalid command $ACTION" >&2
        exit 1
        ;;
esac
