#!/bin/bash

# use to hide password from people having no access to the ssh connection
# based on unique values of you rpi :
#    * based on the mac address of the ethernet card (so, not for rpi0) - not secure for people having access to the local network, but for people having access to your external drive or system.conf file
#    * based on the rpi serial number - limited security while it's only 8 numbers and guessable partially i think

ACTION=$1
CODE=$2

getPassword() {
    SERIAL=$(sed -n -e 's+^Serial[ \t]*: \(.*\)+\1+p' /proc/cpuinfo)
    ETHMAC=$(cat /sys/class/net/eth*/address 2>/dev/null)
    echo "${SERIAL}${ETHMAC}"
}

case "${ACTION}" in
    "decode")
        if [[ "${CODE}" == "enc:"* ]]; then
            PASSWORD=$(getPassword)
            CODE=$(echo "${CODE#enc:}" | openssl enc -aes-128-cbc -pbkdf2 -a -d -salt -pass pass:"${PASSWORD}")
            [ -z "${CODE}" ] && exit 1
        fi
        echo "${CODE}"
    ;;
    "encode")
        PASSWORD=$(getPassword)
        CODE=$(echo "${CODE}" | openssl enc -aes-128-cbc -pbkdf2 -a -salt -pass pass:"${PASSWORD}")
        [ -z "${CODE}" ] && exit 1
        echo "enc:${CODE}"
    ;;
esac

exit 0
