#!/bin/bash 
#
# Suspend or shutdown
#

SUSPEND_MODE="$(/usr/bin/system-settings-get-master system.suspendmode)"
# because on rg552, it is too easy to push on the shutdown button
SHUTDOWNDELAY="$(/usr/bin/system-settings-get-master system.shutdowndelay)"
[ -z "${SHUTDOWNDELAY}" ] && SHUTDOWNDELAY=0

###############################
# 1 when pressed
# 0 when released
SETACTION=$1

do_es_menu() {
    # display the menu only when es is up and no game is running
    HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" "http://localhost:1234/runningGame")
    test $? != 0                 && return 0
    test "${HTTP_STATUS}" != 201 && return 0 # 201 when not game

    curl "http://localhost:1234/quit?confirm=menu"
}

if [ "${SETACTION}" = 1 ]; then
    ### when the button is pressed, if there is no configuration, shutdown immediatly, else wait the release event
    if [ -z "${SUSPEND_MODE}" ] && [ "${SHUTDOWNDELAY}" -eq 0 ]; then
		/sbin/shutdown -h now
    else
		touch "/var/run/shutdown-delay.flag"
		SLEEPTIME=$((SHUTDOWNDELAY + 1))
		sleep ${SLEEPTIME}
		if [ -e "/var/run/shutdown-delay.flag" ]; then
			# the one who manage to remove the file can do the action
			if rm "/var/run/shutdown-delay.flag" 2>/dev/null; then
				touch "/var/run/shutdown-delay.last"
				do_es_menu
	    	fi
		fi
    fi
else
    # the one who manage to remove the file can do the action
    FLAG_DELAY=$(($(date +%s) - $(date +%s -r "/var/run/shutdown-delay.flag")))
    if rm "/var/run/shutdown-delay.flag" 2>/dev/null; then
		# if there is a delay, check it first
		if [ -n "${SHUTDOWNDELAY}" ] && [ "${FLAG_DELAY}" -lt "${SHUTDOWNDELAY}" ]; then
            # no action if the delay didn't elapsed
            exit 0
		fi

		### callable only once every 7 seconds
		### because some boards (steamdeck) have 2 events reacting to the KEY_POWER
		### this is mainly for suspend to not call it 2 times
		if [ -e "/var/run/shutdown-delay.last" ]; then
			DELAY=$(($(date +%s) - $(date +%s -r "/var/run/shutdown-delay.last")))
			if [ "${DELAY}" -lt 5 ]; then
				echo "wait between 2 calls" >2&
				exit 0
			fi
		fi
		touch "/var/run/shutdown-delay.last"
		########

		# shutdown / suspend
		case "${SUSPEND_MODE}" in
			"suspend")
				pm-is-supported --suspend && pm-suspend
				;;
			"hybrid")
				pm-is-supported --suspend-hybrid && pm-suspend-hybrid
				;;
			"hibernate")
				pm-is-supported --hibernate && pm-hibernate
				;;
			*)
				/sbin/shutdown -h now
				;;
		esac
    fi
fi
