#!/bin/dash
DAEMON="tee-supplicant"
PIDFILE="/var/run/$DAEMON.pid"
DAEMON_ARGS="-d /dev/teepriv0"

start() {
	printf 'Starting %s: ' "$DAEMON"
	{ start-stop-daemon -S -q -p "$PIDFILE" -x "/usr/sbin/$DAEMON" -- $DAEMON_ARGS && echo "OK"; } || echo "FAIL"
}

stop() {
	printf 'Stopping %s: ' "$DAEMON"
	{ start-stop-daemon -K -q -p "$PIDFILE" && echo "OK"; } || echo "FAIL"
}

restart() {
	stop
	sleep 1
	start
}

case "$1" in
	start|stop|restart)
		"$1";;
	reload)
		# Restart, since there is no true "reload" feature (does not
		# reconfigure/restart on SIGHUP, just closes all open files).
		restart;;
	*)
		echo "Usage: $0 {start|stop|restart|reload}"
		exit 1
esac
