#!/bin/bash

# We only want to run the script if the board has lid capability
if ! knulli-board-capability "lid"; then
    exit 1
fi

case "$1" in
    start)
            batocera-settings-set system.lid shutdown
        ;;
    stop)
            batocera-settings-set system.lid suspend
        ;;
    *)
        # Code in here will be executed in all other conditions.
        echo "Usage: $0 {start|stop}"
        ;;
esac
 
exit $?
