#!/bin/bash

# We only want to run the script if the board has RGB capability
if ! knulli-board-capability "rgb"; then
    exit 1
fi

case "$1" in
    thaw|resume)
        /usr/bin/knulli-rgb-led-daemon restart
        ;;
esac

exit 0
