#!/bin/sh

# We only want to run the script if the board has lid capability
if ! knulli-board-capability "lid"; then
    exit 1
fi

case "$1" in
    thaw|resume)
        read -r HALLKEY < /sys/class/power_supply/axp2202-battery/hallkey
        if [ "$HALLKEY" = "0" ]; then
            ( sleep 1 && pm-suspend ) &
        fi
        ;;
esac

exit 0
