#!/bin/dash
# Starts audio services

. /etc/profile.d/xdg.sh
. /etc/profile.d/dbus.sh

apply_audioconfig() {
    { [ -n "$2" ] && batocera-audio set-profile "$2"; } || EXITCODE=1
    { [ -n "$1" ] && batocera-audio set "$1"; } || EXITCODE=1

    # Always apply volume last, even if device/profile failed
    batocera-audio setSystemVolume "$3" || return 1
    return "${EXITCODE:-0}"
}

try_apply_audioconfig() {
    N=1
    while [ "$N" -lt 11 ] && ! apply_audioconfig "$1" "$2" "$3"
    do
        sleep 2
        echo "Retry applying audio ($N)" >&2
        N=$((N + 1))
    done
    if [ "$N" -lt 11 ]; then
        echo "Audio config: OK"
        return 0
    else        
        echo "Audio config: FAIL"
        return 1
    fi
}

stop_audioconfig() {
    VOLUME=$(batocera-audio getSystemVolume)
    [ -n "$VOLUME" ] && /usr/bin/regmsg setConfigKey /userdata/system/system.conf audio.volume "$VOLUME"
}

case "$1" in
    start)
        audio_device=$(/usr/bin/regmsg getConfigKey audio.device)
        audio_profile=$(/usr/bin/regmsg getConfigKey audio.profile)
        audio_volume=$(/usr/bin/regmsg getConfigKey audio.volume)
        # backgroud function because some tv or audio cards take longer to initialize
        try_apply_audioconfig "${audio_device:-auto}" "${audio_profile:-auto}" "${audio_volume:-50}" &
        ;;
    stop)
        stop_audioconfig
        ;;
    restart|reload)
        stop;
        start;
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}" >&2
        exit 1
        ;;
esac