# Bootloader
BR2_TARGET_GRUB2=y
BR2_TARGET_GRUB2_BUILTIN_MODULES_EFI="boot linux ext2 fat squash4 part_msdos part_gpt normal efi_gop loadenv hashsum echo halt gcry_sha256 test regexp sleep search search_fs_file search_fs_uuid search_label chain reboot"
BR2_PACKAGE_EFIVAR=y
