diff --git a/Makefile b/Makefile
index 872f1a3900..e07b5ab16b 100644
--- a/Makefile
+++ b/Makefile
@@ -766,10 +766,14 @@ endif
 		{ echo "ERROR: we shouldn't have a /etc/ld.so.conf.d directory"; exit 1; } || true
 	mkdir -p $(TARGET_DIR)/etc
 	( \
-		echo "NAME=Buildroot"; \
-		echo "VERSION=$(BR2_VERSION_FULL)"; \
-		echo "ID=buildroot"; \
-		echo "VERSION_ID=$(BR2_VERSION)"; \
+		echo "NAME=REG-Linux"; \
+		echo "VERSION=$(REGLINUX_SYSTEM_VERSION)"; \
+		echo "ID=$(REGLINUX_SYSTEM_ARCH)"; \
+		echo "VERSION_ID=$(REGLINUX_SYSTEM_ID_VERSION)"; \
+		echo "PRETTY_NAME=\"REG-Linux $(REGLINUX_SYSTEM_VERSION)\""; \
+		echo "BUILD_ID=$(REGLINUX_SYSTEM_BUILD_ID)"; \
+		echo "RELEASE_TYPE=$(REGLINUX_SYSTEM_RELEASE_TYPE)"; \
+		echo "LOGO=reglinux_logo"; \
 		echo "PRETTY_NAME=\"Buildroot $(BR2_VERSION)\"" \
 	) >  $(TARGET_DIR)/usr/lib/os-release
 	ln -sf ../usr/lib/os-release $(TARGET_DIR)/etc
