#!/bin/sh

BOARD=$(cat /boot/boot/system.board)

case $1 in
    start)
	if [ "$BOARD" = "trimui-smart-pro" ]; then
		trimui_inputd_smart_pro &
	elif [ "$BOARD" = "trimui-brick" ]; then
		trimui_inputd_brick &
	fi
	;;
    stop)
	killall -9 trimui_inputd_smart_pro 2>/dev/null || true
	killall -9 trimui_inputd_brick 2>/dev/null || true
	;;
esac

exit 0
