#!/bin/sh

DAEMON=/usr/bin/battery-saver.sh
BATTSAVER_DIR="/var/run/battery-saver/"
PIDFILE=/var/run/battery-saver/battery-saver.pid
DAEMON_NAME=$(basename "$DAEMON")

mkdir -p "$BATTSAVER_DIR"

start_daemon() {
    echo "Starting $DAEMON_NAME."
    if [ -f "$PIDFILE" ] && start-stop-daemon --status --pidfile "$PIDFILE" > /dev/null 2>&1; then
        echo "$DAEMON_NAME is already running."
        exit 0
    fi

    start-stop-daemon --start --quiet --background --make-pidfile --pidfile "$PIDFILE" --exec "$DAEMON" \
        && echo "$DAEMON_NAME started OK" || { echo "$DAEMON_NAME failed to start"; exit 1; }
}

stop_daemon() {
    echo "Stopping $DAEMON_NAME."
    start-stop-daemon --stop --quiet --pidfile "$PIDFILE" \
        && { echo "$DAEMON_NAME stopped"; rm -f "$PIDFILE"; } || { echo "$DAEMON_NAME is not running."; exit 1; }
}

# Sanity check
test -x $DAEMON || exit 0

case "$1" in
    start)
        start_daemon
        ;;
    stop)
        stop_daemon
        ;;
    restart)
        stop_daemon
        sleep 1
        start_daemon
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}" >&2
        exit 1
        ;;
esac
