#!/bin/sh

case "$1" in
    start)
	if [ -x /usr/sbin/plymouthd -a -x /usr/bin/plymouth ]
	then
		plymouthd --graphical-boot --attach-to-session --mode=boot
		plymouth --show-splash
	fi
	;;
    stop)
	# Save the boot log to file and stop splash
	if [ -x /usr/bin/plymouth ] && /usr/bin/plymouth --ping
	then
		plymouth update-root-fs --read-write
		plymouth quit --retain-splash
	fi
        ;;
    *)
esac

exit $?
