#!/bin/bash

# Retrieve command line generated by configgen
cmdline=/usr/bin/emulatorlauncher.py "-command start $@"`

# Execute it
bash -c "${cmdline}"

# Retrieve PID file contents, wait for it
#PIDFile=/var/run/game.pid
#GamePID=$(<"$PIDFile")
#/usr/bin/waitpid $GamePID

# Clear PID file
#rm /var/run/game.pid

# Stop properly
/usr/bin/emulatorlauncher.py "-command stop $@"
