#!/bin/bash
case "$1" in
  start|stop|restart|reload)
    ;;
  status)
    [ "$(/usr/bin/system-settings-get system.nfs.enabled)" = "1" ] && echo "NFS status: enabled" || echo "NFS status: disabled"
    ;;
  enabled)
      /usr/bin/system-settings-set system.nfs.enabled 1
      /etc/init.d/S60nfs start
    ;;
  disabled)
      /etc/init.d/S60nfs stop
      /usr/bin/system-settings-set system.nfs.enabled 0
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|reload|enabled|disabled|status}"
    exit 1
esac
