#!/bin/dash
#
# nfs           This shell script takes care of starting and stopping
#               the NFS services. Stolen from RedHat FC5.

[ "$(/usr/bin/regmsg getConfigKey system.nfs.enabled)" != "1" ] && exit 0

NR_THREADS=2
[ -f /etc/default/nfsd ] && . /etc/default/nfsd

start() {
	mkdir -p /var/lock/subsys /run/nfs/sm /run/nfs/sm.bak
	touch /run/nfs/rmtab
	# Start daemons.
	echo -n "Starting NFS statd: "
	{ rpc.statd && echo "OK"; } || echo "FAIL"
	touch /var/lock/subsys/nfslock
	echo -n "Starting NFS services: "
	{ /usr/sbin/exportfs -r && echo "OK"; } || echo "FAIL"
	echo -n "Starting NFS daemon: "
	{ rpc.nfsd ${NR_THREADS} && echo "OK"; } || echo "FAIL"
	echo -n "Starting NFS mountd: "
	{ rpc.mountd && echo "OK"; } || echo "FAIL"
	touch /var/lock/subsys/nfs
}

stop() {
	# Stop daemons.
	echo -n "Shutting down NFS mountd: "
	{ killall -q rpc.mountd 2>/dev/null && echo "OK"; } || echo "FAIL"
	echo -n "Shutting down NFS daemon: "
	{ killall -q nfsd 2>/dev/null && echo "OK"; } || echo "FAIL"
	echo -n "Shutting down NFS services: "
	{ /usr/sbin/exportfs -au && echo "OK"; } || echo "FAIL"
	echo -n "Stopping NFS statd: "
	{ killall -q rpc.statd 2>/dev/null && echo "OK"; } || echo "FAIL"
	rm -f /var/lock/subsys/nfs /var/run/rpc.statd.pid /var/lock/subsys/nfslock
}

case "$1" in
	start)	start ;;
	stop)	stop  ;;
	restart)
		stop
		start
		;;
	reload)
		/usr/sbin/exportfs -r
		touch /var/lock/subsys/nfs
		;;
	*)
		echo "Usage: $0 {start|stop|restart|reload}"
		exit 1
esac
