################################################################################
#
# libretro-melonds
#
################################################################################
# Version: Commits on Oct 21, 2024
LIBRETRO_MELONDS_VERSION = 7a3c11ff970cd36ca806961fae6db94b30dd5401
LIBRETRO_MELONDS_SITE = $(call github,libretro,melonds,$(LIBRETRO_MELONDS_VERSION))
LIBRETRO_MELONDS_LICENSE = GPLv2
LIBRETRO_MELONDS_DEPENDENCIES = libpcap

ifeq ($(BR2_PACKAGE_HAS_LIBGL),y)
LIBRETRO_MELONDS_DEPENDENCIES += libgl
endif

ifeq ($(BR2_PACKAGE_HAS_LIBGLES),y)
LIBRETRO_MELONDS_DEPENDENCIES += libgles
endif

LIBRETRO_MELONDS_PLATFORM = $(LIBRETRO_PLATFORM)
LIBRETRO_MELONDS_EXTRA_ARGS =

ifeq ($(BR2_PACKAGE_SYSTEM_TARGET_BCM2711),y)
LIBRETRO_MELONDS_PLATFORM = rpi4_64

else ifeq ($(BR2_PACKAGE_SYSTEM_TARGET_BCM2712),y)
LIBRETRO_MELONDS_PLATFORM = rpi5_64

else ifeq ($(BR2_cortex_a55),y)
LIBRETRO_MELONDS_PLATFORM = odroidc4

else ifeq ($(BR2_cortex_a35),y)
LIBRETRO_MELONDS_PLATFORM = odroidgoa

else ifeq ($(BR2_PACKAGE_SYSTEM_TARGET_RK3399),y)
LIBRETRO_MELONDS_PLATFORM = RK3399

else ifeq ($(BR2_PACKAGE_SYSTEM_TARGET_RK3588),y)
LIBRETRO_MELONDS_PLATFORM = RK3588

else ifeq ($(BR2_PACKAGE_SYSTEM_TARGET_MT8395),y)
LIBRETRO_MELONDS_PLATFORM = RK3588

else ifeq ($(BR2_PACKAGE_SYSTEM_TARGET_S922X)$(BR2_PACKAGE_SYSTEM_TARGET_A3GEN2),y)
LIBRETRO_MELONDS_PLATFORM = odroidn2

else ifeq ($(BR2_PACKAGE_SYSTEM_TARGET_H616)$(BR2_PACKAGE_SYSTEM_TARGET_H700)$(BR2_PACKAGE_SYSTEM_TARGET_S905GEN2),y)
LIBRETRO_MELONDS_PLATFORM = orangepizero2

else ifeq ($(BR2_PACKAGE_SYSTEM_TARGET_H6),y)
LIBRETRO_MELONDS_PLATFORM = orangepizero2

else ifeq ($(BR2_PACKAGE_SYSTEM_TARGET_ASAHI),y)
LIBRETRO_MELONDS_PLATFORM = saphira

else ifeq ($(BR2_PACKAGE_SYSTEM_TARGET_SDM845),y)
LIBRETRO_MELONDS_PLATFORM = sdm845

else ifeq ($(BR2_PACKAGE_SYSTEM_TARGET_SM8250),y)
LIBRETRO_MELONDS_PLATFORM = sm8250

else ifeq ($(BR2_PACKAGE_SYSTEM_TARGET_SM8550),y)
LIBRETRO_MELONDS_PLATFORM = sm8250

else ifeq ($(BR2_aarch64),y)
LIBRETRO_MELONDS_PLATFORM = unix

else ifeq ($(BR2_x86_64),y)
LIBRETRO_MELONDS_EXTRA_ARGS += ARCH=x86_64
endif

define LIBRETRO_MELONDS_BUILD_CMDS
	$(TARGET_CONFIGURE_OPTS) $(MAKE) LDFLAGS="-lrt" CXX="$(TARGET_CXX)" CC="$(TARGET_CC)" -C $(@D)/ \
	    -f Makefile platform="$(LIBRETRO_MELONDS_PLATFORM)" $(LIBRETRO_MELONDS_EXTRA_ARGS) \
        GIT_VERSION="-$(shell echo $(LIBRETRO_MELONDS_VERSION) | cut -c 1-7)"
endef

define LIBRETRO_MELONDS_INSTALL_TARGET_CMDS
	$(INSTALL) -D $(@D)/melonds_libretro.so \
		$(TARGET_DIR)/usr/lib/libretro/melonds_libretro.so
endef

$(eval $(generic-package))
