#!/bin/sh

CONFIGFILE=/boot/config.txt

f_usage() {
    echo "${0} gpicase" >&2
    echo "${0} gpicase2" >&2
    echo "${0} gpicase2w" >&2
}

do_config(){
    setup="# ====== GPi Case setup section =====
    ${video}
    dtparam=act_led_trigger=none
    dtparam=act_led_activelow=on
    # ====== GPi Case setup section end ====="

    echo "${setup}" | (
    while read LINE
    do
        if ! grep -qE "^${LINE}$" "${CONFIGFILE}"
        then
            mount -o remount,rw /boot
            echo "${LINE}" >> "${CONFIGFILE}"
        fi
    done
    )
    >&2 echo "${ACTION} support installed!"
    >&2 echo "Please reboot the system so that the changes take effect!"
}

if [ $# -eq 0 ]; then
    f_usage
    exit 1
fi

ACTION=$1

case "${ACTION}" in
    "gpicase")
        video="dtoverlay=retroflag-gpicase"
        do_config
    ;;
    "gpicase2")
        video="dtoverlay=retroflag-gpicase2"
        do_config
    ;;
    "gpicase2w")
        video="dtoverlay=retroflag-gpicase2w"
        do_config
    ;;
    *)
        f_usage
        >&2 echo "error: invalid command ${ACTION}"
        exit 1
esac
exit 0
