#!/bin/dash

# Redirect output to log
exec >>/userdata/system/logs/emulationstation.log 2>&1

case "$1" in
start)
    . /etc/profile.d/xdg.sh
    . /etc/profile.d/dbus.sh

    /usr/bin/plymouth quit

    if [ "$(/usr/bin/regmsg systemconf getConfigKey system.es.atstartup)" != "0" ]; then
        if [ "$XDG_SESSION_TYPE" = "wayland" ]; then
            WLR_LIBINPUT_NO_DEVICES=1 /usr/bin/sway &
        else
            %REGLINUX_EMULATIONSTATION_CMD% %REGLINUX_EMULATIONSTATION_POSTFIX%
        fi
    fi
    ;;
stop)
    emulationstation-standalone --stop-rebooting
    pkill -f sway
    pkill -f emulationstation

    i=0 # Wait up to 5 seconds for emulationstation to exit
    while pgrep -f emulationstation >/dev/null ; do
        [ $i -gt 20 ] && break
        sleep 0.25
        i=$((i + 1))
    done
    # Change scren to "GAME OVER"
    /usr/sbin/plymouthd --mode=shutdown --graphical-boot --attach-to-session && /usr/bin/plymouth --show-splash
    ;;
restart|reload)
    "$0" stop
    "$0" start
    ;;
*)
    exec echo "Usage: $0 {start|stop|restart}"
    exit 1
    ;;
esac
