#!/bin/sh

# system-mount [FSTYPE] [RWREQUIRED] [MOUNTDEVICE] [MOUNTPOINT]

if test $# -ne 4
then
    echo "${0} [FSTYPE] [RWREQUIRED] [MOUNTDEVICE] [MOUNTPOINT]" >&2
    exit 1
fi

FSTYPE="$1"
RWREQUIRED="$2"
MOUNTDEVICE="$3"
MOUNTPOINT="$4"
FSMOUNTOPT="noatime"
TESTFILE="${MOUNTPOINT}/reglinux.fsrw.test"

do_mount() {
    case "${FSTYPE}" in
        ntfs)
            if test -n "$(ntfsinfo -m "${MOUNTDEVICE}" 2>&1 | grep 'Volume is scheduled for check.')"; then
                ntfsfix -d "${MOUNTDEVICE}"
            fi
            if modprobe ntfs3; then
                if ! mount -t ntfs3 "${MOUNTDEVICE}" "${MOUNTPOINT}" -o "${FSMOUNTOPT}"; then
                    exit 1
                fi
            else
                if ! modprobe fuse || ! mount -t ntfs-3g "${MOUNTDEVICE}" "${MOUNTPOINT}" -o "${FSMOUNTOPT}"; then
                    exit 1
                fi
            fi
            ;;
        btrfs)
            modprobe btrfs
            if mount -t btrfs "${MOUNTDEVICE}" "${MOUNTPOINT}" -o "${FSMOUNTOPT}"; then
                exit 0
            fi
            exit 1
            ;;
        vfat|exfat)
            modprobe "${FSTYPE}"
            FSMOUNTOPT="${FSMOUNTOPT},iocharset=utf8"
            if ! mount "${MOUNTDEVICE}" "${MOUNTPOINT}" -o "${FSMOUNTOPT}"; then
                exit 1
            fi
            ;;
        *)
            # ext4
            if mount "${MOUNTDEVICE}" "${MOUNTPOINT}" -o "${FSMOUNTOPT}"; then
                exit 0
            fi
            exit 1
            ;;
    esac
}

# try to mount
do_mount

if test "${RWREQUIRED}" != "1"; then
    exit 0 # success even if it's readonly
fi

# check if the fs is rw because in some case, even if asked rw, fs will be mount in ro because of ntfs errors
if touch "${TESTFILE}"; then
    rm "${TESTFILE}"
    exit 0 # we can write
fi

# try to fix. It doesn't work in 100% of the case : in the worst case, you've to plug on a windows environement and run an fsck
if ! umount "${MOUNTPOINT}"; then
    exit 1
fi

# write it on the terminal while it can take time
case "${FSTYPE}" in
    "exfat")
        fsck.exfat -p "${MOUNTDEVICE}" > /dev/tty0
    ;;
    "vfat")
        fsck.vfat -a "${MOUNTDEVICE}" > /dev/tty0
    ;;
    "ntfs")
        ntfsfix -d "${MOUNTDEVICE}" > /dev/tty0
    ;;
esac

# try to mount again
do_mount

# new try to write
if touch "${TESTFILE}"; then
    rm "${TESTFILE}"
else
    umount "${MOUNTPOINT}"
    exit 1    # we really wanted RW
fi

exit 0
