#!/bin/sh

# system-mount [FSTYPE] [RWREQUIRED] [MOUNTDEVICE] [MOUNTPOINT]

if test $# -ne 4
then
    echo "${0} [FSTYPE] [RWREQUIRED] [MOUNTDEVICE] [MOUNTPOINT]" >&2
    exit 1
fi

FSTYPE="$1"
RWREQUIRED="$2"
MOUNTDEVICE="$3"
MOUNTPOINT="$4"
FSMOUNTOPT="noatime"
TESTFILE="${MOUNTPOINT}/reglinux.fsrw.test"

do_mount() {
    case "${FSTYPE}" in
        exfat)
            # required for exfat
            # note that we can't just put in /etc/modules.conf because it is loaded too late after udev and share mounting
            modprobe fuse
            if ! mount.exfat "${MOUNTDEVICE}" "${MOUNTPOINT}" -o "${FSMOUNTOPT}"; then
                exit 1
            fi
        ;;
        vfat)
            FSMOUNTOPT="${FSMOUNTOPT},iocharset=utf8,flush"
            if ! mount "${MOUNTDEVICE}" "${MOUNTPOINT}" -o "${FSMOUNTOPT}"; then
                exit 1
            fi
        ;;
        ntfs)
            if test -e "/sbin/mount.ntfs-3g"; then
                /sbin/mount.ntfs-3g "${MOUNTDEVICE}" "${MOUNTPOINT}" -o "${FSMOUNTOPT}" || exit 1
            else
                mount -t ntfs3 "${MOUNTDEVICE}" "${MOUNTPOINT}" -o "${FSMOUNTOPT}" || exit 1
            fi
        ;;
        btrfs)
            if mount -t btrfs "${MOUNTDEVICE}" "${MOUNTPOINT}" -o "${FSMOUNTOPT}"; then
                exit 0
            fi
            exit 1
        ;;
        *)
            # ext4
            if mount "${MOUNTDEVICE}" "${MOUNTPOINT}" -o "${FSMOUNTOPT}"; then
                exit 0
            fi
            exit 1
        ;;
    esac
}

# try to mount
do_mount

if test "${RWREQUIRED}" != 1; then
    exit 0 # success even if it's readonly
fi

# check if the fs is rw because in some case, even if asked rw, fs will be mount in ro because of ntfs errors
if touch "${TESTFILE}"; then
    rm "${TESTFILE}"
    exit 0 # we can write
fi

# try to fix. It doesn't work in 100% of the case : in the worst case, you've to plug on a windows environement and run an fsck
if ! umount "${MOUNTPOINT}"; then
    exit 1
fi

# write it on the terminal while it can take time
case "${FSTYPE}" in
    "exfat")
        fsck.exfat -p "${MOUNTDEVICE}" > /dev/tty0
    ;;
    "vfat")
        fsck.vfat -a "${MOUNTDEVICE}" > /dev/tty0
    ;;
    "ntfs")
        ntfsfix "${MOUNTDEVICE}" > /dev/tty0
    ;;
esac

# try to mount again
do_mount

# new try to write
if touch "${TESTFILE}"; then
    rm "${TESTFILE}"
else
    umount "${MOUNTPOINT}"
    exit 1    # we really wanted RW
fi

exit 0
