#!/bin/bash

# the only partition we know when booting from linux is the root device on which linux booted.
# usually, the share partition is the next partition on the same disk
# 1 : the boot partition
# 2 : the share partition (user data)
#
# the root partition is not always /dev/mmcblk0p1, mainly in case you boot from an usb stick or a hard drive

determine_X_part() {
    sed -n -e "s|\(^[^ ].*\) ${1} .*$|\1|p" /proc/mounts
}

determine_default_share_part() {
  BOOTPART=$(determine_X_part "/boot")
  BOOTDISKPREFIX=$(determine_part_prefix "$BOOTPART")
  SHAREPART=$(blkid -o device -t LABEL=SHARE "$BOOTDISKPREFIX"*)                # Make sure it is in the same disk
  [ -n "${SHAREPART#"${SHAREPART%[0-9]}"}" ] && echo "$SHAREPART" || exit 1     # Check that is a number

}

determine_default_share_part_num() {
  BOOTPART=$(determine_X_part "/boot")
  BOOTDISKPREFIX=$(determine_part_prefix "$BOOTPART")
  SHAREPART=$(blkid -o device -t LABEL=SHARE "$BOOTDISKPREFIX"*)
  [ -n "${SHAREPART#"${SHAREPART%[0-9]}"}" ] && echo "${SHAREPART#"${SHAREPART%[0-9]}"}" || exit 1
}

determine_part_prefix() {
  # /dev/mmcblk0p3 => /dev/mmcblk0
  # /dev/sda1      => /dev/sda
  [ -n "${1#"${1%p[0-9]}"}" ] && echo "${1%p[0-9]}" || echo "${1%[0-9]}"
}

PARTNAME=$1

case "${PARTNAME}" in
  "boot")
    determine_X_part /boot
  ;;

  "share_internal")
    determine_default_share_part
  ;;

  "share_internal_num")
    determine_default_share_part_num
  ;;

  "share")
    determine_X_part /userdata
  ;;

  "prefix")
    determine_part_prefix "$2"
  ;;

  *)
    echo "${0} <boot|share_internal|share_internal_num|share|prefix x>" >&2
    echo "  boot: the REG Linux boot partition" >&2
    echo "  share_internal: the REG Linux share internal partition " >&2
    echo "  share_internal_num: the number of share_internal partition" >&2
    echo "  share: the REG Linux share partition " >&2
    echo "  prefix x: the disk of the partition x (without the partition number)" >&2
    exit 1
  ;;
esac

exit 0
