################################################################################
#
# Azahar libretro core
#
################################################################################

LIBRETRO_AZAHAR_VERSION = 2125.0-rc1
LIBRETRO_AZAHAR_SITE = https://github.com/azahar-emu/azahar.git
LIBRETRO_AZAHAR_SITE_METHOD = git
LIBRETRO_AZAHAR_GIT_SUBMODULES=YES
LIBRETRO_AZAHAR_LICENSE = GPLv2
LIBRETRO_AZAHAR_DEPENDENCIES += fmt boost ffmpeg sdl2 fdk-aac
LIBRETRO_AZAHAR_SUPPORTS_IN_SOURCE_BUILD = NO

LIBRETRO_AZAHAR_GIT_SUBMODULES = YES

LIBRETRO_AZAHAR_BUILD_TYPE = Release

LIBRETRO_AZAHAR_CONF_OPTS += -DCMAKE_BUILD_TYPE=$(LIBRETRO_AZAHAR_BUILD_TYPE)
LIBRETRO_AZAHAR_CONF_OPTS += -DBUILD_SHARED_LIBS=OFF
LIBRETRO_AZAHAR_CONF_OPTS += -DENABLE_LIBRETRO=ON
LIBRETRO_AZAHAR_CONF_OPTS += -DENABLE_SDL2=OFF
LIBRETRO_AZAHAR_CONF_OPTS += -DENABLE_QT=OFF
LIBRETRO_AZAHAR_CONF_OPTS += -DENABLE_SDL2_FRONTEND=OFF
LIBRETRO_AZAHAR_CONF_OPTS += -DENABLE_TESTS=OFF
LIBRETRO_AZAHAR_CONF_OPTS += -DENABLE_ROOM_STANDALONE=OFF
LIBRETRO_AZAHAR_CONF_OPTS += -DENABLE_WEB_SERVICE=OFF
LIBRETRO_AZAHAR_CONF_OPTS += -DENABLE_OPENAL=OFF
LIBRETRO_AZAHAR_CONF_OPTS += -DUSE_DISCORD_PRESENCE=OFF
LIBRETRO_AZAHAR_CONF_OPTS += -DAZAHAR_WARNINGS_AS_ERRORS=OFF
LIBRETRO_AZAHAR_CONF_OPTS += -DAZAHAR_ENABLE_COMPATIBILITY_REPORTING=ON
LIBRETRO_AZAHAR_CONF_OPTS += -DENABLE_COMPATIBILITY_LIST_DOWNLOAD=ON
LIBRETRO_AZAHAR_CONF_OPTS += -DUSE_SYSTEM_BOOST=ON
LIBRETRO_AZAHAR_CONF_OPTS += -DUSE_SYSTEM_SDL2=ON
LIBRETRO_AZAHAR_CONF_OPTS += -DCITRA_ENABLE_BUNDLE_TARGET=ON
LIBRETRO_AZAHAR_CONF_OPTS += -DCITRA_WARNINGS_AS_ERRORS=OFF
LIBRETRO_AZAHAR_CONF_OPTS += -DDYNARMIC_WARNINGS_AS_ERRORS=OFF
LIBRETRO_AZAHAR_CONF_OPTS += -DENABLE_LTO=ON

# Use SSE 4.2 code paths on x86_64_v3 build
ifeq ($(BR2_x86_x86_64_v3),y)
LIBRETRO_AZAHAR_CONF_OPTS += -DENABLE_SSE42=ON
else
LIBRETRO_AZAHAR_CONF_OPTS += -DENABLE_SSE42=OFF
endif

# Vulkan support
ifeq ($(BR2_PACKAGE_XWAYLAND)$(BR2_PACKAGE_REGLINUX_VULKAN),yy)
    LIBRETRO_AZAHAR_DEPENDENCIES += vulkan-headers xwayland
    LIBRETRO_AZAHAR_CONF_OPTS += -DENABLE_VULKAN=ON
else
    LIBRETRO_AZAHAR_CONF_OPTS += -DENABLE_VULKAN=OFF
endif

LIBRETRO_AZAHAR_CONF_ENV += LDFLAGS=-lpthread

define LIBRETRO_AZAHAR_INSTALL_TARGET_CMDS
    	mkdir -p $(TARGET_DIR)/usr/lib/libretro
    $(INSTALL) -D $(@D)/buildroot-build/bin/$(LIBRETRO_AZAHAR_BUILD_TYPE)/azahar_libretro.so \
    	$(TARGET_DIR)/usr/lib/libretro
endef

$(eval $(cmake-package))
