################################################################################
#
# libretro-mupen64plus-next
#
################################################################################
# Version: Commits on Jan 27, 2025
LIBRETRO_MUPEN64PLUS_NEXT_VERSION = 3a676196500545b637b83cb19fb393d2359e1f9d
LIBRETRO_MUPEN64PLUS_NEXT_SITE = $(call github,libretro,mupen64plus-libretro-nx,$(LIBRETRO_MUPEN64PLUS_NEXT_VERSION))
LIBRETRO_MUPEN64PLUS_NEXT_LICENSE = GPLv2
LIBRETRO_MUPEN64PLUS_NEXT_DEPENDENCIES = host-nasm

LIBRETRO_MUPEN64PLUS_NEXT_TARGET_CFLAGS = $(TARGET_CFLAGS)
LIBRETRO_MUPEN64PLUS_NEXT_TARGET_CXXFLAGS = $(TARGET_CXXFLAGS)
LIBRETRO_MUPEN64PLUS_NEXT_TARGET_LDFLAGS = $(TARGET_LDFLAGS)

# Architecture
ifeq ($(BR2_x86_64),y)
LIBRETRO_MUPEN64PLUS_NEXT_EXTRA_ARGS = ARCH=x86_64 HAVE_PARALLEL_RSP=1 HAVE_PARALLEL_RDP=1 HAVE_THR_AL=1 LLE=1
else ifeq ($(BR2_arm),y)
LIBRETRO_MUPEN64PLUS_NEXT_EXTRA_ARGS = ARCH=arm HAVE_NEON=1
else ifeq ($(BR2_aarch64),y)
LIBRETRO_MUPEN64PLUS_NEXT_EXTRA_ARGS = ARCH=aarch64
endif

# OpenGL backend
ifeq ($(BR2_PACKAGE_HAS_LIBGL),y)
        LIBRETRO_MUPEN64PLUS_NEXT_DEPENDENCIES += libgl
else ifeq ($(BR2_PACKAGE_HAS_GLES3),y)
        LIBRETRO_MUPEN64PLUS_NEXT_DEPENDENCIES += libgles
        LIBRETRO_MUPEN64PLUS_NEXT_EXTRA_ARGS += FORCE_GLES3=1 GL_LIB=-lGLESv2
else ifeq ($(BR2_PACKAGE_HAS_GLES2),y)
        LIBRETRO_MUPEN64PLUS_NEXT_DEPENDENCIES += libgles
        LIBRETRO_MUPEN64PLUS_NEXT_EXTRA_ARGS += FORCE_GLES=1 GL_LIB=-lGLESv2
endif

# EGL
ifeq ($(BR2_PACKAGE_MESA3D_OPENGL_EGL),y)
	LIBRETRO_MUPEN64PLUS_NEXT_TARGET_CFLAGS += -DEGL_NO_X11
	LIBRETRO_MUPEN64PLUS_NEXT_TARGET_CXXFLAGS += -DEGL_NO_X11
endif

# Platform
ifeq ($(BR2_aarch64),y)
LIBRETRO_MUPEN64PLUS_NEXT_PLATFORM = $(LIBRETRO_PLATFORM) arm64
else
LIBRETRO_MUPEN64PLUS_NEXT_PLATFORM = $(LIBRETRO_PLATFORM)
endif

define LIBRETRO_MUPEN64PLUS_NEXT_BUILD_CMDS
	$(TARGET_CONFIGURE_OPTS) \
		CFLAGS="$(LIBRETRO_MUPEN64PLUS_NEXT_TARGET_CFLAGS)" \
		CXXFLAGS="$(LIBRETRO_MUPEN64PLUS_NEXT_TARGET_CXXFLAGS)" \
		LDFLAGS="$(LIBRETRO_MUPEN64PLUS_NEXT_TARGET_LDFLAGS)" \
		$(MAKE) CXX="$(TARGET_CXX)" CC="$(TARGET_CC)" -C $(@D)/ -f Makefile platform="$(LIBRETRO_MUPEN64PLUS_NEXT_PLATFORM)" \
		BOARD="$(LIBRETRO_MUPEN64PLUS_NEXT_BOARD)" $(LIBRETRO_MUPEN64PLUS_NEXT_EXTRA_ARGS) \
        GIT_VERSION="-$(shell echo $(LIBRETRO_MUPEN64PLUS_NEXT_VERSION) | cut -c 1-7)"
endef

define LIBRETRO_MUPEN64PLUS_NEXT_INSTALL_TARGET_CMDS
	$(INSTALL) -D $(@D)/mupen64plus_next_libretro.so \
		$(TARGET_DIR)/usr/lib/libretro/mupen64plus-next_libretro.so
endef

$(eval $(generic-package))
